blank_issues_enabled: false
contact_links:
  - name: Management question / usage question
    url: ../../#management-security-and-privacy
    about: For questions about using the stick, first see the operations manual in docs/generated.
